name: test Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    #services:
      #mysql:
        #image: mysql:5.7
        #env:
          #MYSQL_DATABASE: spring_users_mysql
          #MYSQL_ALLOW_EMPTY_PASSWORD: yes

        #ports:
          #- 3306:3306
        #options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
       - uses: actions/checkout@v2
       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
           java-version: '17'
           distribution: 'zulu'

       - name: Build Docker Image
         run: docker-compose build

       - name: Start containers
         run: |
           docker-compose up -d
           sleep 10
           docker-compose ps

       - name: Build with Maven
         run: mvn package -DskipTests

       - name: Run Application
         run: java -jar target/crud-users-mysql-0.0.1-SNAPSHOT.jar


       - name: Run curl to analyze endpoints
         run: curl http://localhost:8080/api/users

       - name: Stop containers
         run: |
          docker-compose stop
          docker-compose rm -f